### ISSUE TITLE
Consider using DOMHighResTimestamp instead of DOMTimeStamp

### ISSUE THREAD

**Issue by yoavweiss** [w3c/geolocation-api#103]
We're considering our options RE `DOMTimeStamp`, and wondering what it's used for. It seems less well-defined than `DOMHighResTimestamp`. Would y'all consider switching over?

See heycam/webidl#2 for discussion.

**Comment by marcoscaceres** [comment]
We probably can’t switch because of web compat. It’s used to determine the age of the acquired position. 

But we could rename it LegacyGeolocationTimeStamp as it’s just a typedef and define it as used by the API. That could finally kill it from the platform.

**Comment by yoavweiss** [comment]
Geolocation is [not the only user today](https://github.com/heycam/webidl/issues/2#issuecomment-909030799). Agree that renaming it may prevent new users though.

**Comment by marcoscaceres** [comment]
Ah, my bad. Those WICG ones should be easy to update at least.
