### ISSUE TITLE
Transition to Proposed Recommendation

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/geolocation-api#121]
To transition to PR, we need to:

- [x] close off #120

**Comment by marcoscaceres** [comment]
@anssiko, @reillyeon, @xfq, I'd like to formally start the transition process to Proposed Rec. 

@xfq, I'll file the initial transition request... just to get things rolling.

**Comment by xfq** [comment]
Although the likelihood of objections is low, we still need a CfC for publishing this spec as a PR.

**Comment by anssiko** [comment]
@marcoscaceres I'd like to include in the CfC a proof of adequate implementation experience.

The optimal way to do so would be to reference https://wpt.fyi/geolocation-API but this introduces a dependency on WebDriver not implemented in Firefox and Safari. Are you planning to produce a manual implementation report that could be referenced, perhaps accompanied with manual tests for parts that currently depend on WebDriver? Once this aspect is clarified, I'll send a CfC.

**Comment by marcoscaceres** [comment]
No, my plan is to just run with it as is and explain it to the Director. Then, in parallel, try to get the WebDriver parts implemented in Gecko and WebKit. That’s obviously going to take more time, but it shouldn’t block progressing to PR.

**Comment by anssiko** [comment]
@marcoscaceres @reillyeon, does the following describe the situation accurately:

>Geolocation API test suite [4] depends on certain features of the WebDriver browser automation framework only implemented in Chromium. Due to this, the test report [5] currently shows a substantial number of test failures. We expect the currently reported Chrome and Edge test failures to be fixed prior to transition to Proposed Recommendation, but we do not expect Firefox and Safari to implement the said WebDriver features in time for this Proposed Recommendation transition due to substantial amount of work. To that end, we plan to seek an exception from the Director for the Proposed Recommendation transition when we are able to demonstrate that the automated tests pass on Chromium-based browsers and are able to demonstrate interoperability with Firefox and Safari by other means, for example, manual testing.
>
>[4] https://github.com/web-platform-tests/wpt/tree/master/geolocation-API
>[5] https://wpt.fyi/geolocation-API

This is an excerpt I plan to include in the CfC to explain the situation to the Working Group and its key stakeholders.

The reason why I'm stressing this point is that the "adequate implementation experience" is tested as "must show" at Proposed Recommendation transition time and the AC will be asking the WG to show evidence when they are asked to review the Proposed Recommendation.

**Comment by marcoscaceres** [comment]
About: 

> We expect the currently reported Chrome and Edge test failures to be fixed prior to transition to Proposed Recommendation

I think that’s optimistic/ideal, but not strictly necessary (unless we get commitment from someone to step up and help us on the Chrome side in a timely manner! 🙏 ). I fear we might be waiting a long time though. 

That’s why I’d be ok to just show things manually or just link directly to patches. We have patches for everything that got updated (I wrote most of the patches + unit tests for Gecko and a handful in WebKit, IIRC)… so I’m confident about interop, specially given the recent test rewrite.

**Comment by reillyeon** [comment]
On the Chromium side I'm taking a look at our internal test runners to make sure the tests Marcos added to WPT are working even if the WebDriver stuff is broken (internal Chromium tests don't use WebDriver). Chromium also has internal tests which use a more advanced test-only API to exercise API behavior: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/wpt_internal/geolocation-api/

So, even with the existing WebDriver API for permissions control fixed we probably still need to expose WebDriver's [setGeoLocation](http://v4.webdriver.io/api/mobile/setGeoLocation.html) method through the test_driver API so that when run in automation these tests can actually provide location in a reliable way.

**Comment by marcoscaceres** [comment]
> Chromium also has internal tests which use a more advanced test-only API to exercise API behavior:

heh, my job here is done! 😜 

What's interesting is that was able to run through the tests manually.

**Comment by marcoscaceres** [comment]
Fixed the comment above... accidentally pressed the green button early.

**Comment by anssiko** [comment]
I started a CfC and included a description of the current issue with test automation: https://lists.w3.org/Archives/Public/public-device-apis/2022Mar/0005.html

**Comment by marcoscaceres** [comment]
Closing as done.

**Comment by BORNSICK1** [comment]
I don't think you have the right person

________________________________
