### ISSUE TITLE
Support floorLevel on GeolocationCoordinates?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/geolocation-api#122]
It appears WebKit has a `GeolocationCoordinates.prototype.floorLevel`:

 * `[EnabledBySetting=GeolocationFloorLevelEnabled] readonly attribute unrestricted double? floorLevel;`

Which appears to be enabled by default in Safari. 

I'm wondering if any other engine will want to support that also in future version of the spec (after we go to REC)?

**Comment by sahdinagaradipa** [comment]
https://github.com/w3c/geolocation-api/issues/122#issue-1142435682

**Comment by Ahmad-S792** [comment]
@marcoscaceres - 

https://github.com/w3c/geolocation-api/issues/15#issuecomment-631896781

**Comment by marcoscaceres** [comment]
Closing as this can’t be implemented on other platforms apparently. We can revisit if that changes.

**Comment by navv-christofer-flores** [comment]
HI there! 👋  QQ, is there any plans on integrating this ? Safari has this available because they do have a way to use Core Location features within their browser (or any WebKit based browser) when using Geolocation inside a venue they have fingerprinted, so wonder if this would be available?
