### ISSUE TITLE
Background Geolocation via Service Workers

### ISSUE THREAD

**Issue by RichardMaher** [w3c/geolocation-api#13]
Whether you're into jogging, or cycling and want to track your trips, or you manage a fleet of trucks, farm or mining vehicles or delivery bikes you need to track your geographical position whilst your Web App is backgrounded or your device is asleep.

Push messages from servers notifying you of a GeoFence boundary traversal is also something that relies on background GeoLocation sending location updates to the server. How else can your Ski buddies know which piste you're on at the moment?

My proposal for this feature has been discussed at length here: -
[Service Worker](https://github.com/w3c/ServiceWorker/issues/745 )

I am very keen to discuss this further in either location and desolated to receive the following email. Please say it ain't so? We need you!

Dear Advisory Committee Representative,
Chairs,
Geolocation Working Group members,

The Geolocation Working Group [1] is now closed.

The mission of the group was to define a secure and privacy-sensitive interface for using client-side location information in location-aware Web applications.

It published an update to the Geolocation API document as a Recommendation:
     https://www.w3.org/TR/2016/REC-geolocation-API-20161108/

The work on the DeviceOrientation Event Specification [2] did not complete however, due to unresolved issues related to security and privacy. We believe this work would benefit from increased participation and alignment with the work of the Device and Sensors (DAS) Working Group [3]. As such, we are looking at getting the specification adopted by that Working Group.

Further maintenance around the Geolocation documents is expected to happen with the Device and Sensors Working Group [3].

W3C thanks the group Chair, Giridhar Mandyam (Qualcomm Innovation Center), and all the participants in the group for their efforts.

This announcement follows section 5.2.7 of the Process Document:
  https://www.w3.org/2017/Process-20170301/#GeneralTermination

Thank you,

For Tim Berners-Lee, Director;
Xueyuan Jia, W3C Marketing & Communications

[1] https://www.w3.org/2008/geolocation/
[2] https://www.w3.org/TR/2016/CR-orientation-event-20160818/
[3] https://www.w3.org/2009/dap/

**Comment by cerw** [comment]
Any update on this ?

**Comment by Alaa-Ellethey** [comment]
+1

**Comment by kleeb** [comment]
+1

**Comment by MatanYed** [comment]
+1

**Comment by marcoscaceres** [comment]
Closing, as this repo only deals with maintaining the Geolocation API and not what is being proposed here.
