### ISSUE TITLE
get location API not working on android webview

### ISSUE THREAD

**Issue by kaominghsu** [w3c/geolocation-api#132]
I have a get location web on Android webview,but it's not workgin
I use Javascript the api on web
「navigator.geolocation.watchPosition」「navigator.geolocation.getCurrentPosition」

I test the situation
get location web on chrome,get GPS
get location web on android webview ,No response, GPS no get

machine environment:
android version 12 SKQ1.210908.001
MIUI 13.0.6.0

**Comment by reillyeon** [comment]
This is not an appropriate forum for reporting implementation issues. Android WebView bugs may be reported here: https://bugs.chromium.org/p/chromium/issues/entry?template=Webview+Bugs
