### ISSUE TITLE
What does "decimal degrees" mean?

### ISSUE THREAD

**Issue by mgiuca** [w3c/geolocation-api#135]
The phrase "decimal degrees" appears three times in the spec in relation to lat/long coordinates:

> The `latitude` and `longitude` attributes are geographic coordinates specified in decimal degrees.

I'm not sure if "decimal" has a specific meaning here in context, but it seems incorrect to use it in the context of a numeric value. Numeric values are only "decimal" in terms of being converted to/from strings; there's nothing "decimal" about a number as it exists in the JavaScript context.

Propose that the word "decimal" is removed from the spec?

**Comment by reillyeon** [comment]
https://en.wikipedia.org/wiki/Decimal_degrees

I don't know if there's a good normative reference for this. It is implied by the value being defined as a float and could also be referred to as "fractions of degrees" perhaps without reference to a definition of the term.

**Comment by chaals** [comment]
Why not just define this (perhaps by reference) in the spec. I've seen enough examples of people failing to translate between different measurement schemes that it seems this should be highlighted, rather than assuming the whole world works with the same assumptions.

**Comment by jyasskin** [comment]
https://en.wikipedia.org/wiki/Decimal_degrees says it's a notation—i.e. a text format—which as @mgiuca says isn't a great description of the numeric value stored in these attributes. I'd lean toward @mgiuica's suggestion as being the shortest option: "... coordinates specified in degrees". If it's important to be really clear that these aren't integers, we could use "... coordinates specified as a real number of degrees", but I think the WebIDL type is clear enough that we don't need that extra length.

However, if someone who works with WGS84 professionally says I'm wrong, they're probably right. :)
