### ISSUE TITLE
Define "geographic coordinates"

### ISSUE THREAD

**Issue by mgiuca** [w3c/geolocation-api#136]
The spec uses the term "geographic coordinates" without defining it or referencing another spec:

> The `latitude` and `longitude` attributes are geographic coordinates specified in decimal degrees.

I noticed that `altitude` is defined in terms of the WGS84 spec but lat/long are not. The "geographic coordinates" presumably refer to standard latitude/longitude coordinates in degrees, but it would be good to explicitly specify these, so it's clear:

* What + and - lat means (presumably N and S respectively).
* What + and - long means (presumably W and E).
* What 0 long means (presumably London).

I assume this is defined in WGS84 so it would be good to simply reference that.

**Comment by reillyeon** [comment]
The non-normative [Scope](https://w3c.github.io/geolocation-api/#scope) section says that the position information is provided in terms of WGS84, but only the `altitude` property is normatively defined in terms of those format. The `latitude` and `longitude` properties should also be normatively defined as WGS84 coordinates.

**Comment by marcoscaceres** [comment]
Closed by https://github.com/w3c/geolocation-api/pull/138
