### ISSUE TITLE
need help- with the use of geolocation how can i make a tracking device

### ISSUE THREAD

**Issue by krishnaasx** [w3c/geolocation-api#140]
so basically i am  making a project that'll be able to track the users position (with keep in mind the privacy of user i will provide the feature for the user to disable the tracking). so please give me an idea how should i approach making this.

**Comment by anssiko** [comment]
This repository is dedicated for discussion about the specification development. This is not the right forum to seek help on how to use the API.

For guidance on how to use the API, please refer to the [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API/Using_the_Geolocation_API) and [web.dev](https://web.dev/articles/user-location) articles instead, or do a targeted search for more ideas. If you get stuck, https://stackoverflow.com/ is a helpful place where web developers share their solutions and answer questions from other web developers.
