### ISSUE TITLE
Add support for converting Geolocation Position+Coordinates to JSON (object)

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/geolocation-api#145]
Given `GeolocationCoordinates` are just nullable doubles, it would be nice if GeolocationCoordinates exposed a (WebIDL) default `.toJSON()` method.

**Comment by reillyeon** [comment]
That would be nice given that `JSON.stringify()` does not work on `GeolocationCoordinates`.

**Comment by marcoscaceres** [comment]
Another question is if we should also add a `toJSON()` method on `GeolocationPosition`? I don't know if there is much value to getting the timestamp...

**Comment by reillyeon** [comment]
Less value but it would still feel weird if you could stringify the coordinates but not the full object passed to your callback so I say yes, let's add a `toJSON()` method to both interfaces.

**Comment by marcoscaceres** [comment]
Sounds good.
