### ISSUE TITLE
Set up process and markers for updating the Proposed Edited Recommendation

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/geolocation-api#148]
We need to just double check that we have a clear change log.

Where we can, we should be marking up where things have changed (the purple boxes :( )...

**Comment by marcoscaceres** [comment]
Actually, looking at https://w3c.github.io/tr-design/src/README#amendment ... it remains completely and utterly unworkable. We absolutely won't be doing any of that.

If people want to look at the what's change, they can look at the change log like everyone else.

We should, at least, just make sure the commit messages are prefixed with:

 * Correction:
 * Addition: 
 
But that's it. 

If anyone complains, we can drop the spec back to WD, and quickly move it through CR and REC (for a day) and back to WD. That's also what we are doing to Payment Request because the above process is so terrible.

**Comment by saschanaz** [comment]
Maybe that's for old ages where specs didn't have public github repositories? Is there some relevant open issue in tr-design?
