### ISSUE TITLE
repo name nit: it'd be nice if this were simply w3c/geolocation

### ISSUE THREAD

**Issue by hober** [w3c/geolocation-api#154]

**Comment by marcoscaceres** [comment]
Agree. I’ll rename it and set up some redirects.

**Comment by himorin** [comment]
https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository
I suppose renaming and adding new as the same repo name will kill all auto-redirects (of issues, etc.)... no?

**Comment by marcoscaceres** [comment]
It should address all the issues, yes.

**Comment by marcoscaceres** [comment]
we would need to add it to:
https://github.com/w3c/w3c.github.io

@himorin, could you do it for us? 🙏

**Comment by marcoscaceres** [comment]
We should probably rename the spec to just "Geolocation" too, while we are at it.

**Comment by marcoscaceres** [comment]
Sent PR https://github.com/w3c/w3c.github.io/pull/124

**Comment by himorin** [comment]
added missing ones https://github.com/w3c/w3c.github.io/pull/125
