### ISSUE TITLE
Only allow to ask for location on user interaction

### ISSUE THREAD

**Issue by jimmywarting** [w3c/geolocation-api#16]
I get numerous of popups asking me to allow sharing my position on initial page load. It's freaking annoying. It's a bad behavior.

Here is the thing. I don't always know what they will use it for so the obvious choice is block them. which is not good. it might come in handy later and by then it's already blocked.

Google search ask for permission also...

It's better to allow it when i want to utilize the functionality like getting direction from point A to B. At least then i know what it will be used for when i'm clicking the "Use my location" button

Cause for making an issue: The worse traveling website I sometime need to use
[SL - Storstockholm Local Transport](https://sl.se/en)

**Comment by plehegar** [comment]
it's really up to the website to indicate how they'll use the information. The browser cannot know that and therefore cannot pop anything meaningful here unfortunately. Ideally, we need to come up with a better permission framework overall.

**Comment by jimmywarting** [comment]
The [Permission api](https://github.com/w3c/permissions/issues/77) comes to mind. Talks about only allowing permissions.request() on user interaction

Wish we only used that permission api to ask for all kinds of usage. Geolocation, push, webcam, etc

**Comment by plehegar** [comment]
that's the goal of the Device and Sensors group as well as providing a generic sensor API. But it's getting a low adoption by browsers at the moment so it's trailing behind:
  https://w3c.github.io/sensors/#permissions
