### ISSUE TITLE
Enable tls for gh-pages

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/geolocation-api#28]
For when viewing the spec over gh-pages, it would be great if tls could be enabled... in particular, ReSpec relies on some APIs that need SecureContext, otherwise some warnings appear.

**Comment by anssiko** [comment]
Thanks for catching this. Just ticked the following box:

* [x] Enforce HTTPS

**Comment by marcoscaceres** [comment]
Awesome, ty!
