### ISSUE TITLE
Move to WICG

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/geolocation-api#29]
Hi, just noticed https://github.com/w3c/geolocation-api/commit/4cba5ba9bbdb49ca31362b83517db53e07fbb216

And also the SoTD listing the WICG as owners? 

However, I think I missed the memo about the WICG taking it? Could you help me understand what the plan is? Was there a Discourse thread about that... apologies if there was, just cannot recall.

**Comment by reillyeon** [comment]
I thought it moved into the Devices and Sensors WG but I think I'm confusing this with `GeolocationSensor`.

**Comment by marcoscaceres** [comment]
That would make more sense. For updates to Geolocation, it would be really helpful if there were tracking bugs to update the changes in each engine. If we are planning on doing minor maintenance on the spec (in a backwards compatible manner), then it would be great to involve Mozilla. I can ask to join the group, but I need justification/rationale for the changes being made to this ye olde API.

**Comment by anssiko** [comment]
This is what we agreed at [DAS WG rechartering](https://www.w3.org/2019/03/devices-sensors-wg-charter.html) time (15 March 2019):

>The Working Group will maintain errata and new editions, as necessary, for the Geolocation API, the Vibration API, and HTML Media Capture W3C Recommendations.

Wgid was updated https://github.com/w3c/geolocation-api/commit/d56a6c6b74cbf3d2972d0c0ce6b44f4b957ced41 but we apparently missed the ReSpec.js metadata, proposed fix #30.

**Comment by anssiko** [comment]
In addition, we welcome @marcoscaceres to the group, as well as help with maintenance of this spec.
