### ISSUE TITLE
Editor's Draft is not listed in W3C

### ISSUE THREAD

**Issue by saschanaz** [w3c/geolocation-api#35]
https://www.w3.org/TR/?title=geolocation

Searching W3C only shows the REC but not ED, and thus affects [Reffy](https://github.com/tidoust/reffy-reports/blob/master/w3c/idl/geolocation-API.idl) where it cannot get the latest spec bits.

Not sure how it could be updated, but could you register it?

**Comment by anssiko** [comment]
@xfq can you help make sure Reffy finds Geolocation API ED?

**Comment by xfq** [comment]
@deniak Could you have a look at this?

**Comment by deniak** [comment]
/TR now displays the geolocation API ED.

**Comment by xfq** [comment]
Thank you, @deniak!

**Comment by saschanaz** [comment]
I can only see Geolocation Sensor ED but not Geolocation API, should I wait a few hours maybe?

**Comment by deniak** [comment]
sorry, there was a caching issue. It should be good now.
