### ISSUE TITLE
Watch process refers to undefined step 6

### ISSUE THREAD

**Issue by DavidWiesner** [w3c/geolocation-api#44]
The section [4.1](https://w3c.github.io/geolocation-api/#dfn-acquisition-steps) of the watch process refers to a step 6 that is not defined. 

https://github.com/w3c/geolocation-api/blob/db83e5fbe9ab388fb5effc79b8f2b66c48acfd09/index.html#L564-L566

**Comment by marcoscaceres** [comment]
Looks like that should be step 5, not 6.

**Comment by anssiko** [comment]
This is a case where linking to a step number breaks the algorithm when it evolves. For future-proofing, let’s make the step 5 a dfn with a descriptive name and link to it.
