### ISSUE TITLE
Section 1: Editorial - possible syntax error

### ISSUE THREAD

**Issue by magnus-git** [w3c/geolocation-api#53]
During the security review, in example 4 in introduction: 
navigator.geolocation.getCurrentPosition(successCallback, errorCallback, {  maximumAge: 600000, });
The comma after 600000 seems spurious.

**Comment by reillyeon** [comment]
Trailing commas are not syntax errors in Javascript. Leaving a trailing comma in a multi-line object literal makes it easier to add new keys without modifying nearby lines.
