### ISSUE TITLE
Suggest permission lifetimes?

### ISSUE THREAD

**Issue by pes10k** [w3c/geolocation-api#69]
Permission lifetime for geolocaiton should be aggressively life-timed, given how sensitive the data is, and how easy it is for users to not remove a permission once its been granted (particularly since current browser UX makes it much easier to grant permission than to revoke it).

For example, when iOS made it easier for users to restrict the lifetime of location permissions in apps, [users reduced how much location information they sent by 68%](https://www.fastcompany.com/90454921/apple-and-googles-tough-new-location-privacy-controls-are-working).  This suggests that the current "forever" permission lifetime for location is harming user privacy, and that the spec should similarly restrict the availably and lifetime of this data.

**Comment by marcoscaceres** [comment]
Closing as the spec relies on Permission spec.  Filed https://github.com/w3c/permissions/issues/233

**Comment by anssiko** [comment]
The DAS WG made the following related [resolution](https://www.w3.org/2021/04/06-das-minutes.html#r03) at its 06 April 2021	virtual meeting:

>RESOLUTION: Expand Privacy and Security considerations with discussion of privacy harms from long-lived permissions and Gather developer feedback on restricted lifetime and scope of geolocation capabilities.

@pes10k please confirm whether you are satisfied with the resolution so we can proceed accordingly.

**Comment by marcoscaceres** [comment]
As I wasn't able to join that call, I wasn't able to be make my voice heard when the resolution was proposed. The above resolution applies generally to all permissions, so the appropriate place for them is in the Permission spec.

**Comment by pes10k** [comment]
Hi @anssiko, thank you for the follow up, but no, that resolution is not satisfactory to me.  The request / resolution for this issue is for *normative* changes to the spec to address the discussed privacy harms related to sites having access to geolocation capability for longer than users realize

**Comment by marcoscaceres** [comment]
I've now sent along a PR that defines lifetimes for permissions:
https://github.com/w3c/permissions/pull/287

And I've made a recommendation that specifications that define themselves as "powerful features", such as Geolocation, SHOULD include some RECOMMENDATION about the lifetime of a permission. 

Once the PR above lands, then for Geolocation, we could recommend that geolocation's permission lifetime default to life of the browsing context, with the option of it being extended for a day. We might recommend against the lifetime being indefinite.

**Comment by yoavweiss** [comment]
As a user, I'd be super annoyed if my regular mapping web app re-asked me for permissions every day. I strongly suggest that any recommendation would also consider frequency of use.

**Comment by tomayac** [comment]
+1, any recommendation should definitely be tied to usage.

**Comment by marcoscaceres** [comment]
Yeah, agree. It need to be carefully worded. These are just recommendations.  

We can probably update the text in w3c/permissions#287 also, so that browser heuristics are taken into consideration.

**Comment by marcoscaceres** [comment]
Just for reference, Firefox (session VS indefinite): 
![Screen Shot 2021-08-31 at 6 29 31 pm](https://user-images.githubusercontent.com/870154/131469504-4cfa578d-908f-405c-8f5f-5eb5192c825b.png)

Chrome:
![Screen Shot 2021-08-31 at 6 33 40 pm](https://user-images.githubusercontent.com/870154/131470185-9014719e-6ff0-4009-8b9a-dc8e18f209c8.png)

Safari is session or 1 day: 
![Screen Shot 2021-08-31 at 6 30 51 pm](https://user-images.githubusercontent.com/870154/131469738-f2348300-c776-4125-9f97-82d771fac5e8.png)

As I stated in w3c/permissions#287, I don't want to lock us into anything (this is for security UX teams that know better than standards weenies). Any lock-in would be "un-good".

**Comment by marcoscaceres** [comment]
And for completeness, Brave, which provides a cute little drop down with a bunch of time options:

![Screen Shot 2021-08-31 at 6 40 54 pm](https://user-images.githubusercontent.com/870154/131471317-24bbda38-9320-4601-b425-4389a51db365.png)

**Comment by marcoscaceres** [comment]
@yoavweiss, @tomayac, about: 
> any recommendation should definitely be tied to usage.

I just don't know if all browsers have that level of heuristic baked in (i.e., site usage frequency/frecency, which sounds like a fancy Chrome thing to have... although I think Safari has some internal heuristics for permissions... not necessarily for geo... I don't know if Firefox has any built in fanciness) - so we can't assume that. We should capture that there might be heuristics, also cater for time based too.

**Comment by johannhof** [comment]
Firefox doesn't use heuristics for this. I agree that we should be a bit hand-wavy (or avoid a recommendation) on the part that specifies how browsers should derive the lifetime, to cater to differences between browsers and to encourage innovation.

**Comment by anssiko** [comment]
This looks like a good TPAC discussion topic so I added to https://github.com/w3c/devicesensors-wg/issues/47

**Comment by marcoscaceres** [comment]
Hoping we can have it resolved before TPAC - but maybe good as a general thing to talk about, as there are quite a few DAS specs to which something like this might apply.

**Comment by anssiko** [comment]
I'm a happy chair if the issues I put on the agenda resolve themselves before the meeting.

We discussed this at our 2021 Q2 virtual meeting too, so good to have a checkpoint and also discuss whether this generalizes to other APIs, what we have learned.

**Comment by samuelweiler** [comment]
> I've now sent along a PR that defines lifetimes for permissions:
> [w3c/permissions#287](https://github.com/w3c/permissions/pull/287)
> 
> And I've made a recommendation that specifications that define themselves as "powerful features", such as Geolocation, SHOULD include some RECOMMENDATION about the lifetime of a permission.
> 
> Once the PR above lands, then for Geolocation, we could recommend that geolocation's permission lifetime default to life of the browsing context, with the option of it being extended for a day. We might recommend against the lifetime being indefinite.

It seems like the Geolocation API could make a recommendation now, even before the PR lands in the permissions spec.  @pes10k, any thoughts on this more recent discussion?

**Comment by pes10k** [comment]
I think the text in w3c/permissions#287 looks appealing, and I dig the suggestion of hooking Geolocation into it once it lands.  However, I agree with @samuelweiler that until (if?) both of those changes land in permissions and geolocation, it seems appropriate to include that text in geolocation

**Comment by marcoscaceres** [comment]
Ok, put up some draft text at https://github.com/w3c/geolocation-api/pull/108 

Please make suggestions/improvements inline in the pull request.
