### ISSUE TITLE
Multiple specs per repo is problematic. 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/geolocation-api#7]
This repo should be renamed "geofencing-api"

@darobin, can you rename it?

**Comment by marcoscaceres** [comment]
Actually, I lied... the geolocation spec lives here too... This is not ideal. Having multiple APIs per repo is  problematic. Makes it difficult to file bugs and generally track what is going on. Maybe all the stuff related to geofencing should migrate to a new repo (w3c/geofencing-api).

**Comment by darobin** [comment]
Yes, I recommend you start a new repo. One per spec!

**Comment by marcoscaceres** [comment]
@mkruisselbrink is that ok?

**Comment by mkruisselbrink** [comment]
I agree that it probably makes sense to have these in separate repositories. Unfortunately I didn't figure this out until after pushing geofencing stuff here. When I asked Giri about this I was told this:
"We may have to create a new repo eventually.  Right now, we are only working on one spec actively so I don’t think there is an issue.  But I’ll also verify with the W3C."

**Comment by marcoscaceres** [comment]
Let's just do it now, otherwise we risk losing history, etc.

**Comment by mkruisselbrink** [comment]
Yes, agreed. Who do we have to talk to to make this happen?

**Comment by marcoscaceres** [comment]
@darobin is the right person :) He can make it happen.

**Comment by gmandyam** [comment]
Thanks in advance to Robin for creating the new repo.  In order to stay consistent with other W3C repo's, should it be w3c/geolocation-geofencing?  For instance, the Media Capture TF repo's are titled w3c/mediacapture-main, w3c/mediacapture-image, etc.

**Comment by ashimura** [comment]
I'll work with Robin, Marijin and Giri for this :)

**Comment by ashimura** [comment]
@marcoscaceres , @mkruisselbrink , @gmandyam , @darobin , I'd agree the new repository should be "geofencing-api".  Is that OK?

**Comment by marcoscaceres** [comment]
On Saturday, March 28, 2015, ashimura <notifications@github.com> wrote:

> @marcoscaceres <https://github.com/marcoscaceres> , @mkruisselbrink
> <https://github.com/mkruisselbrink> , @gmandyam
> <https://github.com/gmandyam> , @darobin <https://github.com/darobin> ,
> I'd agree the new repository should be "geofencing-api". Is that OK?
>

Whatever you like and is easy to remember/find. It's easy to change names
later if we ever need to.

**Comment by gmandyam** [comment]
geofencing-api it is then.  I can't create the repo, as I don't seem to have rights.  Kaz or Robin - can you?

**Comment by ashimura** [comment]
I've just created a repo named geofencing-api at:
 https://github.com/w3c/geofencing-api
and added write permission for it to the Geo editors team.

**Comment by mkruisselbrink** [comment]
Okay, I pushed the geofencing spec (with mostly full history) to the new repo, and deleted the spec from here. Somebody with the right permissions should change the geofencing-api repo to have 'gh-pages' as its default branch though (and probably delete the 'master' branch).

**Comment by darobin** [comment]
I've changed the default page, you can delete master if you want.

**Comment by ashimura** [comment]
Thanks, @darobin !

**Comment by plehegar** [comment]
Only one spec remains here.
