### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by xfq** [w3c/geolocation-api#70]
https://w3c.github.io/geolocation-api/#request-position

The link to "non-secure context" is 404.

**Comment by xfq** [comment]
The test suite link in the spec metadata header doesn't seem to work either.

**Comment by marcoscaceres** [comment]
The "non-secure context" is a ReSpec bug 🙀 ... working on fixing it.

**Comment by marcoscaceres** [comment]
About the test suite... will change. 

We also need to change the implementation report link... that implementation report is way out of date. Plus some of the tests are no good... I'll need to rewrite those as a followup.

**Comment by marcoscaceres** [comment]
Fixed the non-secure context linking issue.
