### ISSUE TITLE
Broken fragments

### ISSUE THREAD

**Issue by xfq** [w3c/geolocation-api#71]
https://w3c.github.io/geolocation-api/#request-position

The links to "visible" and "hidden" are broken.

**Comment by marcoscaceres** [comment]
Thanks! Will fix those too.

**Comment by marcoscaceres** [comment]
To fix, we need to republish Page Visibility: https://github.com/w3c/page-visibility/issues/65

**Comment by marcoscaceres** [comment]
filed https://github.com/w3c/transitions/issues/332 to transition Page Visibility.

**Comment by marcoscaceres** [comment]
With Page Visibility now republished, these are now fixed.
