### ISSUE TITLE
Permissions Policy integration incomplete

### ISSUE THREAD

**Issue by annevk** [w3c/geolocation-api#75]
It doesn't perform the "is allowed to use" check anywhere.

**Comment by marcoscaceres** [comment]
so, we had it, but apparently this is covered by the Permission Spec's "request permission to use" algorithm: 

https://github.com/w3c/geolocation-api/pull/68#discussion_r599940995

cc @jyasskin, in case we need to clarify things.

**Comment by annevk** [comment]
Oh I see, https://www.w3.org/TR/permissions/#reading-current-states ends up looking at it. Interesting.

**Comment by marcoscaceres** [comment]
Yeah, let us know if that works ok. We can update Permissions or here if needed.

**Comment by annevk** [comment]
I think that works. There might be some cleanup to be done around settings objects, but that's out-of-scope for this issue. Thanks!
