### ISSUE TITLE
Make the API promise compatible

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/geolocation-api#8]
It would be nice if methods of the Geolocation API returned promises when called with no arguments.

**Comment by gmandyam** [comment]
@marcoscaceres 

Refactoring Geolocation API to be promises-based is certainly a worthwhile endeavour in my opinion, but this should be raised on the group mailing list, particularly to gauge browser vendor interest.  It might also require an adjustment of the Geolocation Working Group charter to reflect the new deliverable.  

Generic Sensor API (https://w3c.github.io/sensors/) is considering Geolocation as one of its use cases as well.  Maybe such an effort should be focused on this specification?

**Comment by marcoscaceres** [comment]
> Refactoring Geolocation API to be promises-based is certainly a worthwhile endeavour in my opinion, but this should be raised on the group mailing list, particularly to gauge browser vendor interest. It might also require an adjustment of the Geolocation Working Group charter to reflect the new deliverable. 

Maybe you could point people here? Mailing lists are :(

> Generic Sensor API (https://w3c.github.io/sensors/) is considering Geolocation as one of its use cases as well. Maybe such an effort should be focused on this specification?

I'm still not sure if any browser vendor will actually implement the generic sensor APIs. It seems like a radical departure from what we already have.

**Comment by gmandyam** [comment]
@marcoscaceres 

Now posted to public-geo:  http://lists.w3.org/Archives/Public/public-geolocation/2016Aug/0001.html

Is Moz committed to supporting?

**Comment by marcoscaceres** [comment]
Thanks for adding this. We could be, but doesn't seem others are given the lack of feedback on the list or here. Closing for now.

**Comment by jimmywarting** [comment]
Revisit? :P

**Comment by marcoscaceres** [comment]
Sure, we could tease this out. So, this would only be useful for `.getCurrentPosition()`. 

Potentially, we could just overload: 

```
Promise<GeolocationPosition> getCurrentPosition(optional PositionOptions options = {});
```

If that's distinguishable (in the IDL sense), then it wouldn't be too painful to add. 

However, the problem is that `GeolocationPositionError` is not a JS `Error` or `DOMException`, so won't have a stack for if `await` rejects - so that's a deal breaker. 

Now, we could define a new set of DOMExceptions for geo, but then this becomes effectively a big spec rewrite for something that I'm now not sure adds much value.

**Comment by jimmywarting** [comment]
Uh, it should have used or extended the Error or DOMException in the first place 🤔

**Comment by marcoscaceres** [comment]
Yeah :( Totally... but unfortunately, we didn't know better back in the mid 2000s. 

Wow! Now I' thinking this would make a great Netflix series.
