### ISSUE TITLE
Nit: clearly indicate implementation-defined behavior

### ISSUE THREAD

**Issue by annevk** [w3c/geolocation-api#82]
By xref'ing the term implementation-defined in Infra.

**Comment by marcoscaceres** [comment]
The xrefs to "implementation-defined behavior" are all good, I think. At: 

 * https://w3c.github.io/geolocation-api/#request-position
 * https://w3c.github.io/geolocation-api/#dfn-request-position

Anything else I should clarify there?

**Comment by annevk** [comment]
Sorry (to you and also myself as it took me a while to find it again) for not including it in OP. I meant this step:

> What constitutes a significant change of geographic position is left to the implementation.
