### ISSUE TITLE
Looking for test suite maintainers for geo API

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/geolocation-api#99]
I'm wondering if other folks would be interested in joining me as reviewers of the Geolocation of the Web Platform tests?

The current set of folks assigned have moved onto other fun things. 

I've sent a PR to add myself:
https://github.com/web-platform-tests/wpt/pull/29816

Any other takers? It should be fairly light duty.

**Comment by reillyeon** [comment]
You can add me as well.

**Comment by marcoscaceres** [comment]
We will go with @reillyeon and I for now. However, anyone else wants to join us, please do!
